/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.api

import openservicebroker.model.Catalog
import openservicebroker.JsonSupport.{*, given}
import openservicebroker.FormSerializable
import openservicebroker.FormStyleFormat
import openservicebroker.HeaderSerializable
import openservicebroker.ApiKeyLocation
import openservicebroker.PathStyleFormat
import openservicebroker.PathSerializable
import openservicebroker.CookieSerializable
import openservicebroker.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object CatalogApi:
  def apply(baseUrl: String = "http://example.com"): CatalogApi[openservicebroker.Authorization.NoAuthorization.type] = CatalogApi(baseUrl, openservicebroker.Authorization.NoAuthorization)
  def withBasicAuth(baseUrl: String, username: String, password: String): CatalogApi[openservicebroker.Authorization.BasicAuth] =
    CatalogApi(baseUrl, openservicebroker.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(baseUrl: String, apiKey: String): CatalogApi[openservicebroker.Authorization.ApiKey] =
    CatalogApi(baseUrl, openservicebroker.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(baseUrl: String, token: String): CatalogApi[openservicebroker.Authorization.BearerToken] =
    CatalogApi(baseUrl, openservicebroker.Authorization.BearerToken(token))

case class CatalogApi[Auth <: openservicebroker.Authorization] private (baseUrl: String, authConfig: openservicebroker.Authorization):
  def withBasicAuth(username: String, password: String): CatalogApi[openservicebroker.Authorization.BasicAuth] =
    copy(authConfig = openservicebroker.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): CatalogApi[openservicebroker.Authorization.ApiKey] =
    copy(authConfig = openservicebroker.Authorization.ApiKey(apiKey))

  def withNoAuth: CatalogApi[openservicebroker.Authorization.NoAuthorization.type] =
    copy(authConfig = openservicebroker.Authorization.NoAuthorization)

  def withBearerTokenAuth(token: String): CatalogApi[openservicebroker.Authorization.BearerToken] =
    copy(authConfig = openservicebroker.Authorization.BearerToken(token))

  /**
   * Expected answers:
   *   code 200 : Catalog (catalog response)
   * 
   * Available security schemes:
   *   basicAuth (http)
   * 
   * @param xBrokerAPIVersion version number of the Service Broker API that the Platform will use
   */
  def catalogGet(xBrokerAPIVersion: String)(using Auth <:< openservicebroker.Authorization.BasicAuth): sttp.client4.Request[Either[ResponseException[String], Catalog]] =
    val requestURL =
      uri"$baseUrl/v2/catalog"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(HeaderSerializable.serialize("X-Broker-API-Version", xBrokerAPIVersion, false))
      .auth(authConfig)
      .response(asJson[Catalog])

end CatalogApi