/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.api

import openservicebroker.model.AsyncOperation
import openservicebroker.model.Error
import openservicebroker.model.LastOperationResource
import openservicebroker.model.ServiceInstanceAsyncOperation
import openservicebroker.model.ServiceInstanceProvisionRequestBody
import openservicebroker.model.ServiceInstanceProvisionResponse
import openservicebroker.model.ServiceInstanceResource
import openservicebroker.model.ServiceInstanceUpdateRequestBody
import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*
import openservicebroker.JsonSupport.{*, given}
import openservicebroker.FormSerializable
import openservicebroker.FormStyleFormat
import openservicebroker.HeaderSerializable
import openservicebroker.ApiKeyLocation
import openservicebroker.PathStyleFormat
import openservicebroker.PathSerializable
import openservicebroker.CookieSerializable
import openservicebroker.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object ServiceInstancesApi:
  def apply(baseUrl: String = "http://example.com"): ServiceInstancesApi[openservicebroker.Authorization.NoAuthorization.type] = ServiceInstancesApi(baseUrl, openservicebroker.Authorization.NoAuthorization)
  def withBasicAuth(baseUrl: String, username: String, password: String): ServiceInstancesApi[openservicebroker.Authorization.BasicAuth] =
    ServiceInstancesApi(baseUrl, openservicebroker.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(baseUrl: String, apiKey: String): ServiceInstancesApi[openservicebroker.Authorization.ApiKey] =
    ServiceInstancesApi(baseUrl, openservicebroker.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(baseUrl: String, token: String): ServiceInstancesApi[openservicebroker.Authorization.BearerToken] =
    ServiceInstancesApi(baseUrl, openservicebroker.Authorization.BearerToken(token))

case class ServiceInstancesApi[Auth <: openservicebroker.Authorization] private (baseUrl: String, authConfig: openservicebroker.Authorization):
  def withBasicAuth(username: String, password: String): ServiceInstancesApi[openservicebroker.Authorization.BasicAuth] =
    copy(authConfig = openservicebroker.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): ServiceInstancesApi[openservicebroker.Authorization.ApiKey] =
    copy(authConfig = openservicebroker.Authorization.ApiKey(apiKey))

  def withNoAuth: ServiceInstancesApi[openservicebroker.Authorization.NoAuthorization.type] =
    copy(authConfig = openservicebroker.Authorization.NoAuthorization)

  def withBearerTokenAuth(token: String): ServiceInstancesApi[openservicebroker.Authorization.BearerToken] =
    copy(authConfig = openservicebroker.Authorization.BearerToken(token))

  /**
   * Expected answers:
   *   code 200 : io.circe.Json (OK)
   *   code 202 : AsyncOperation (Accepted)
   *   code 400 : Error (Bad Request)
   *   code 401 : Error (Unauthorized)
   *   code 410 : Error (Gone)
   *   code 422 : Error (Unprocessable Entity)
   * 
   * Available security schemes:
   *   basicAuth (http)
   * 
   * @param xBrokerAPIVersion version number of the Service Broker API that the Platform will use
   * @param instanceId id of instance being deleted
   * @param serviceId id of the service associated with the instance being deleted
   * @param planId id of the plan associated with the instance being deleted
   * @param xBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
   * @param acceptsIncomplete asynchronous deprovision supported
   */
  def serviceInstanceDeprovision(xBrokerAPIVersion: String, instanceId: String, serviceId: String, planId: String, xBrokerAPIOriginatingIdentity: Option[String] = scala.None, acceptsIncomplete: Option[Boolean] = scala.None)(using Auth <:< openservicebroker.Authorization.BasicAuth): sttp.client4.Request[Either[ResponseException[String], io.circe.Json]] =
    val instanceIdPathParam = PathSerializable.serialize("instance_id", instanceId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/v2/service_instances/${instanceIdPathParam}"
        .addParams(FormSerializable.serialize("service_id", serviceId, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("plan_id", planId, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("accepts_incomplete", acceptsIncomplete, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .headers(HeaderSerializable.serialize("X-Broker-API-Version", xBrokerAPIVersion, false))
      .headers(HeaderSerializable.serialize("X-Broker-API-Originating-Identity", xBrokerAPIOriginatingIdentity, false))
      .auth(authConfig)
      .response(asJson[io.circe.Json])

  /**
   * Expected answers:
   *   code 200 : ServiceInstanceResource (OK)
   *   code 404 : Error (Not Found)
   * 
   * Available security schemes:
   *   basicAuth (http)
   * 
   * @param xBrokerAPIVersion version number of the Service Broker API that the Platform will use
   * @param instanceId instance id of instance to fetch
   * @param xBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
   * @param serviceId id of the service associated with the instance
   * @param planId id of the plan associated with the instance
   */
  def serviceInstanceGet(xBrokerAPIVersion: String, instanceId: String, xBrokerAPIOriginatingIdentity: Option[String] = scala.None, serviceId: Option[String] = scala.None, planId: Option[String] = scala.None)(using Auth <:< openservicebroker.Authorization.BasicAuth): sttp.client4.Request[Either[ResponseException[String], ServiceInstanceResource]] =
    val instanceIdPathParam = PathSerializable.serialize("instance_id", instanceId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/v2/service_instances/${instanceIdPathParam}"
        .addParams(FormSerializable.serialize("service_id", serviceId, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("plan_id", planId, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(HeaderSerializable.serialize("X-Broker-API-Version", xBrokerAPIVersion, false))
      .headers(HeaderSerializable.serialize("X-Broker-API-Originating-Identity", xBrokerAPIOriginatingIdentity, false))
      .auth(authConfig)
      .response(asJson[ServiceInstanceResource])

  /**
   * Expected answers:
   *   code 200 : LastOperationResource (OK)
   *              Headers :
   *                Retry-After - Indicates when to retry the request
   *   code 400 : Error (Bad Request)
   *   code 401 : Error (Unauthorized)
   *   code 404 : Error (Not Found)
   *   code 410 : Error (Gone)
   * 
   * Available security schemes:
   *   basicAuth (http)
   * 
   * @param xBrokerAPIVersion version number of the Service Broker API that the Platform will use
   * @param instanceId instance id of instance to find last operation applied to it
   * @param serviceId id of the service associated with the instance
   * @param planId id of the plan associated with the instance
   * @param operation a provided identifier for the operation
   */
  def serviceInstanceLastOperationGet(xBrokerAPIVersion: String, instanceId: String, serviceId: Option[String] = scala.None, planId: Option[String] = scala.None, operation: Option[String] = scala.None)(using Auth <:< openservicebroker.Authorization.BasicAuth): sttp.client4.Request[Either[ResponseException[String], LastOperationResource]] =
    val instanceIdPathParam = PathSerializable.serialize("instance_id", instanceId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/v2/service_instances/${instanceIdPathParam}/last_operation"
        .addParams(FormSerializable.serialize("service_id", serviceId, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("plan_id", planId, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("operation", operation, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .headers(HeaderSerializable.serialize("X-Broker-API-Version", xBrokerAPIVersion, false))
      .auth(authConfig)
      .response(asJson[LastOperationResource])

  /**
   * Expected answers:
   *   code 200 : ServiceInstanceProvisionResponse (OK)
   *   code 201 : ServiceInstanceProvisionResponse (Created)
   *   code 202 : ServiceInstanceAsyncOperation (Accepted)
   *   code 400 : Error (Bad Request)
   *   code 401 : Error (Unauthorized)
   *   code 409 : Error (Conflict)
   *   code 422 : Error (Unprocessable Entity)
   * 
   * Available security schemes:
   *   basicAuth (http)
   * 
   * @param xBrokerAPIVersion version number of the Service Broker API that the Platform will use
   * @param instanceId instance id of instance to provision
   * @param serviceInstanceProvisionRequestBody parameters for the requested service instance provision
   * @param xBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
   * @param acceptsIncomplete asynchronous operations supported
   */
  def serviceInstanceProvision(xBrokerAPIVersion: String, instanceId: String, serviceInstanceProvisionRequestBody: ServiceInstanceProvisionRequestBody, xBrokerAPIOriginatingIdentity: Option[String] = scala.None, acceptsIncomplete: Option[Boolean] = scala.None)(using Auth <:< openservicebroker.Authorization.BasicAuth): sttp.client4.Request[Either[ResponseException[String], ServiceInstanceProvisionResponse]] =
    val instanceIdPathParam = PathSerializable.serialize("instance_id", instanceId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/v2/service_instances/${instanceIdPathParam}"
        .addParams(FormSerializable.serialize("accepts_incomplete", acceptsIncomplete, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .headers(HeaderSerializable.serialize("X-Broker-API-Version", xBrokerAPIVersion, false))
      .headers(HeaderSerializable.serialize("X-Broker-API-Originating-Identity", xBrokerAPIOriginatingIdentity, false))
      .auth(authConfig)
      .body(asJson(serviceInstanceProvisionRequestBody))
      .response(asJson[ServiceInstanceProvisionResponse])

  /**
   * Expected answers:
   *   code 200 : io.circe.Json (OK)
   *   code 202 : ServiceInstanceAsyncOperation (Accepted)
   *   code 400 : Error (Bad Request)
   *   code 401 : Error (Unauthorized)
   *   code 422 : Error (Unprocessable entity)
   * 
   * Available security schemes:
   *   basicAuth (http)
   * 
   * @param xBrokerAPIVersion version number of the Service Broker API that the Platform will use
   * @param instanceId instance id of instance to update
   * @param serviceInstanceUpdateRequestBody parameters for the requested service instance update
   * @param xBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
   * @param acceptsIncomplete asynchronous operations supported
   */
  def serviceInstanceUpdate(xBrokerAPIVersion: String, instanceId: String, serviceInstanceUpdateRequestBody: ServiceInstanceUpdateRequestBody, xBrokerAPIOriginatingIdentity: Option[String] = scala.None, acceptsIncomplete: Option[Boolean] = scala.None)(using Auth <:< openservicebroker.Authorization.BasicAuth): sttp.client4.Request[Either[ResponseException[String], io.circe.Json]] =
    val instanceIdPathParam = PathSerializable.serialize("instance_id", instanceId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/v2/service_instances/${instanceIdPathParam}"
        .addParams(FormSerializable.serialize("accepts_incomplete", acceptsIncomplete, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.PATCH, requestURL)
      .contentType("application/json")
      .headers(HeaderSerializable.serialize("X-Broker-API-Version", xBrokerAPIVersion, false))
      .headers(HeaderSerializable.serialize("X-Broker-API-Originating-Identity", xBrokerAPIOriginatingIdentity, false))
      .auth(authConfig)
      .body(asJson(serviceInstanceUpdateRequestBody))
      .response(asJson[io.circe.Json])

end ServiceInstancesApi