/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker

import openservicebroker.model.*
import java.time.*
import com.github.plokhotnyuk.jsoniter_scala.macros.*
import com.github.plokhotnyuk.jsoniter_scala.core.*
import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*

object JsonSupport extends AdditionalTypeSerializers:
  inline given CodecMakerConfig = CodecMakerConfig.withAllowRecursiveTypes(true)

  inline def deriveJsonCodec[A](using inline config: CodecMakerConfig): JsonValueCodec[A] =
    JsonCodecMaker.make(config)

  given serviceInstanceProvisionRequestBodyCodec: JsonValueCodec[ServiceInstanceProvisionRequestBody] = deriveJsonCodec
  given serviceInstanceProvisionResponseCodec: JsonValueCodec[ServiceInstanceProvisionResponse] = deriveJsonCodec
  given serviceInstanceUpdateRequestBodyCodec: JsonValueCodec[ServiceInstanceUpdateRequestBody] = deriveJsonCodec
  given catalogCodec: JsonValueCodec[Catalog] = deriveJsonCodec
  given serviceBindingResourceCodec: JsonValueCodec[ServiceBindingResource] = deriveJsonCodec
  given serviceBindingRequestCodec: JsonValueCodec[ServiceBindingRequest] = deriveJsonCodec
  given serviceInstanceResourceCodec: JsonValueCodec[ServiceInstanceResource] = deriveJsonCodec
  given lastOperationResourceCodec: JsonValueCodec[LastOperationResource] = deriveJsonCodec
  given serviceBindingResponseCodec: JsonValueCodec[ServiceBindingResponse] = deriveJsonCodec


