/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * See [Service Broker Errors](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-broker-errors) for more details.
   */
case class Error(
  @named("error") error: Option[String] = scala.None,
  @named("description") description: Option[String] = scala.None,
  @named("instance_usable") instanceUsable: Option[Boolean] = scala.None,
  @named("update_repeatable") updateRepeatable: Option[Boolean] = scala.None
)

