/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class LastOperationResource(
  @named("state") state: LastOperationResourceEnums.State,
  @named("description") description: Option[String] = scala.None,
  @named("instance_usable") instanceUsable: Option[Boolean] = scala.None,
  @named("update_repeatable") updateRepeatable: Option[Boolean] = scala.None
)

object LastOperationResourceEnums:
  enum State:
    case `in progress`
    case `succeeded`
    case `failed`

  object State:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given stateCodec: JsonValueCodec[State] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "in progress" => "in progress"
            case "succeeded" => "succeeded"
            case "failed" => "failed"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end LastOperationResourceEnums
