/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Plan(
  @named("id") id: String,
  @named("name") name: String,
  @named("description") description: String,
  /* See [Service Metadata Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata) for more details. */
  @named("metadata") metadata: Option[io.circe.Json] = scala.None,
  @named("maintenance_info") maintenanceInfo: Option[MaintenanceInfo] = scala.None,
  @named("free") free: Option[Boolean] = scala.None,
  @named("bindable") bindable: Option[Boolean] = scala.None,
  @named("schemas") schemas: Option[Schemas] = scala.None,
  @named("maximum_polling_duration") maximumPollingDuration: Option[Int] = scala.None,
  @named("plan_updateable") planUpdateable: Option[Boolean] = scala.None,
  @named("binding_rotatable") bindingRotatable: Option[Boolean] = scala.None
)

