/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Schemas(
  @named("service_instance") serviceInstance: Option[ServiceInstanceSchema] = scala.None,
  @named("service_binding") serviceBinding: Option[ServiceBindingSchema] = scala.None
)

