/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ServiceBindingEndpoint(
  @named("host") host: String,
  @named("ports") ports: Seq[String],
  @named("protocol") protocol: Option[ServiceBindingEndpointEnums.Protocol] = scala.None
)

object ServiceBindingEndpointEnums:
  enum Protocol:
    case `tcp`
    case `udp`
    case `all`

  object Protocol:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given protocolCodec: JsonValueCodec[Protocol] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "tcp" => "tcp"
            case "udp" => "udp"
            case "all" => "all"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end ServiceBindingEndpointEnums
