/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ServiceInstancePreviousValues(
  @named("service_id") serviceId: Option[String] = scala.None,
  @named("plan_id") planId: Option[String] = scala.None,
  @named("organization_id") organizationId: Option[String] = scala.None,
  @named("space_id") spaceId: Option[String] = scala.None
)

