/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ServiceBindingResource(
  @named("metadata") metadata: Option[ServiceBindingMetadata] = scala.None,
  @named("credentials") credentials: Option[io.circe.Json] = scala.None,
  @named("syslog_drain_url") syslogDrainUrl: Option[String] = scala.None,
  @named("route_service_url") routeServiceUrl: Option[String] = scala.None,
  @named("volume_mounts") volumeMounts: Option[Seq[ServiceBindingVolumeMount]] = scala.None,
  @named("endpoints") endpoints: Option[Seq[ServiceBindingEndpoint]] = scala.None,
  @named("parameters") parameters: Option[io.circe.Json] = scala.None
)

