/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ServiceBindingVolumeMount(
  @named("driver") driver: String,
  @named("container_dir") containerDir: String,
  @named("mode") mode: ServiceBindingVolumeMountEnums.Mode,
  @named("device_type") deviceType: ServiceBindingVolumeMountEnums.DeviceType,
  @named("device") device: ServiceBindingVolumeMountDevice
)

object ServiceBindingVolumeMountEnums:
  enum Mode:
    case `r`
    case `rw`

  object Mode:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given modeCodec: JsonValueCodec[Mode] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "r" => "r"
            case "rw" => "rw"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum DeviceType:
    case `shared`

  object DeviceType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given deviceTypeCodec: JsonValueCodec[DeviceType] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "shared" => "shared"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end ServiceBindingVolumeMountEnums
