/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Service(
  @named("name") name: String,
  @named("id") id: String,
  @named("description") description: String,
  @named("bindable") bindable: Boolean,
  @named("plans") plans: Seq[Plan],
  @named("tags") tags: Option[Seq[String]] = scala.None,
  @named("requires") requires: Option[Seq[ServiceEnums.Requires]] = scala.None,
  /* See [Service Metadata Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata) for more details. */
  @named("metadata") metadata: Option[io.circe.Json] = scala.None,
  @named("dashboard_client") dashboardClient: Option[DashboardClient] = scala.None,
  @named("binding_rotatable") bindingRotatable: Option[Boolean] = scala.None,
  @named("plan_updateable") planUpdateable: Option[Boolean] = scala.None
)

object ServiceEnums:
  enum Requires:
    case `syslog_drain`
    case `route_forwarding`
    case `volume_mount`

  object Requires:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
end ServiceEnums
