/**
 * Open Service Broker API
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * The version of the OpenAPI document: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package openservicebroker.model

import com.github.plokhotnyuk.jsoniter_scala.circe.JsoniterScalaCodec.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ServiceInstanceUpdateRequestBody(
  @named("service_id") serviceId: String,
  /* See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details. */
  @named("context") context: Option[io.circe.Json] = scala.None,
  @named("plan_id") planId: Option[String] = scala.None,
  @named("parameters") parameters: Option[io.circe.Json] = scala.None,
  @named("previous_values") previousValues: Option[ServiceInstancePreviousValues] = scala.None
)

